In [1]:
import pandas as pd
import json
import numpy as np

Lendo o arquivo desta forma para tratar os quando houverem registros (dias) com campos ausentes

In [33]:
text=open('./my_weather_data_fahrenheit.json','r')
x=text.read()

y=json.loads(x)
df=pd.DataFrame(y)

In [34]:
df.head()

,time,sunriseTime,sunsetTime,moonPhase,temperatureHigh,temperatureHighTime,temperatureLow,temperatureLowTime,apparentTemperatureHigh,apparentTemperatureHighTime,...,icon,precipIntensity,precipIntensityMax,precipIntensityMaxTime,precipProbability,precipType,pressure,windGust,windGustTime,ozone
0,1547434800,1547453700,1547498640,0.27,90.44,1547484900,74.99,1547514000,98.71,1547484780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1547521200,1547540100,1547585100,0.31,89.28,1547568060,75.74,1547624580,95.79,1547567880,...,partly-cloudy-day,0.0001,0.0004,1.547532e+09,0.16,rain,1014.1,17.70,1.547585e+09,261.3
2,1547607600,1547626560,1547671500,0.34,90.50,1547654280,77.38,1547701380,98.57,1547647560,...,partly-cloudy-day,0.0001,0.0004,1.547614e+09,0.21,rain,1014.4,16.47,1.547674e+09,262.1
3,1547694000,1547712960,1547757900,0.38,89.74,1547740440,76.95,1547790240,97.94,1547740380,...,rain,0.0007,0.0054,1.547777e+09,0.35,rain,1013.6,17.16,1.547768e+09,265.7
4,1547780400,1547799420,1547844300,0.41,89.50,1547827320,76.69,1547883060,97.15,1547820240,...,rain,0.0015,0.0082,1.547781e+09,0.48,rain,1013.2,17.51,1.547841e+09,270.2

In [35]:
df.describe()

,time,sunriseTime,sunsetTime,moonPhase,temperatureHigh,temperatureHighTime,temperatureLow,temperatureLowTime,apparentTemperatureHigh,apparentTemperatureHighTime,...,apparentTemperatureMax,apparentTemperatureMaxTime,precipIntensity,precipIntensityMax,precipIntensityMaxTime,precipProbability,pressure,windGust,windGustTime,ozone
count,3.650000e+02,3.650000e+02,3.650000e+02,365.000000,365.000000,3.650000e+02,365.000000,3.650000e+02,365.000000,3.650000e+02,...,365.000000,3.650000e+02,364.000000,364.000000,3.640000e+02,364.000000,364.000000,364.000000,3.640000e+02,364.000000
mean,1.563160e+09,1.563179e+09,1.563222e+09,0.499041,86.427479,1.563204e+09,74.773699,1.563256e+09,93.470603,1.563202e+09,...,93.470603,1.563202e+09,0.004961,0.017186,1.563237e+09,0.343956,1013.826648,17.835659,1.563253e+09,264.670055
std,9.116121e+06,9.115599e+06,9.115930e+06,0.284051,2.507817,9.115246e+06,2.088078,9.113609e+06,4.564015,9.115782e+06,...,4.564015,9.115782e+06,0.008999,0.045999,9.089898e+06,0.265530,1.959726,3.619155,9.090207e+06,6.883734
min,1.547435e+09,1.547454e+09,1.547499e+09,0.000000,79.130000,1.547485e+09,69.090000,1.547514e+09,82.300000,1.547485e+09,...,82.300000,1.547485e+09,0.000000,0.000200,1.547532e+09,0.020000,1009.800000,8.740000,1.547585e+09,248.900000
25%,1.555297e+09,1.555317e+09,1.555360e+09,0.260000,84.440000,1.555344e+09,73.000000,1.555401e+09,89.670000,1.555344e+09,...,89.670000,1.555344e+09,0.000600,0.002300,1.555426e+09,0.130000,1012.300000,15.167500,1.555423e+09,259.675000
50%,1.563160e+09,1.563180e+09,1.563222e+09,0.500000,86.800000,1.563206e+09,74.990000,1.563263e+09,93.170000,1.563201e+09,...,93.170000,1.563201e+09,0.001750,0.007700,1.563223e+09,0.250000,1013.300000,17.720000,1.563260e+09,264.350000
75%,1.571022e+09,1.571040e+09,1.571084e+09,0.740000,88.540000,1.571062e+09,76.620000,1.571102e+09,97.370000,1.571062e+09,...,97.370000,1.571062e+09,0.006000,0.020425,1.571044e+09,0.502500,1015.100000,20.257500,1.571067e+09,270.000000
max,1.578884e+09,1.578903e+09,1.578948e+09,0.990000,91.530000,1.578931e+09,78.400000,1.578977e+09,103.550000,1.578931e+09,...,103.550000,1.578931e+09,0.087800,0.811500,1.578899e+09,0.990000,1019.200000,28.850000,1.578958e+09,280.400000

In [36]:
temperatures = [column for column in df.columns if column.count('emperature') > 0 and column.count('ime') == 0]
temperatures

['temperatureHigh',
 'temperatureLow',
 'apparentTemperatureHigh',
 'apparentTemperatureLow',
 'temperatureMin',
 'temperatureMax',
 'apparentTemperatureMin',
 'apparentTemperatureMax']

In [37]:
def apply(registro):
    return registro.apply(lambda x: round((x - 32) * 5/9, ndigits=2))

In [38]:
df[temperatures].head()

,temperatureHigh,temperatureLow,apparentTemperatureHigh,apparentTemperatureLow,temperatureMin,temperatureMax,apparentTemperatureMin,apparentTemperatureMax
0,90.44,74.99,98.71,76.86,74.99,90.44,76.86,98.71
1,89.28,75.74,95.79,77.78,76.61,89.28,78.36,95.79
2,90.50,77.38,98.57,79.38,75.74,90.50,77.78,98.57
3,89.74,76.95,97.94,78.94,77.38,89.74,79.38,97.94
4,89.50,76.69,97.15,78.61,76.95,89.50,78.94,97.15

In [39]:
df[temperatures] = df[temperatures].apply(apply, axis=1)

In [40]:
df[temperatures]

,temperatureHigh,temperatureLow,apparentTemperatureHigh,apparentTemperatureLow,temperatureMin,temperatureMax,apparentTemperatureMin,apparentTemperatureMax
0,32.47,23.88,37.06,24.92,23.88,32.47,24.92,37.06
1,31.82,24.30,35.44,25.43,24.78,31.82,25.76,35.44
2,32.50,25.21,36.98,26.32,24.30,32.50,25.43,36.98
3,32.08,24.97,36.63,26.08,25.21,32.08,26.32,36.63
4,31.94,24.83,36.19,25.89,24.97,31.94,26.08,36.19
...,...,...,...,...,...,...,...,...
360,30.34,24.83,34.32,25.85,24.81,30.34,25.83,34.32
361,31.13,24.51,34.12,25.60,24.83,31.13,25.85,34.12
362,31.33,23.91,34.78,24.91,24.51,31.33,25.60,34.78
363,31.28,24.80,34.25,25.94,23.91,31.28,24.91,34.25
364,31.59,25.43,36.32,26.42,24.80,31.59,25.94,36.32

In [41]:
df.head()

,time,sunriseTime,sunsetTime,moonPhase,temperatureHigh,temperatureHighTime,temperatureLow,temperatureLowTime,apparentTemperatureHigh,apparentTemperatureHighTime,...,icon,precipIntensity,precipIntensityMax,precipIntensityMaxTime,precipProbability,precipType,pressure,windGust,windGustTime,ozone
0,1547434800,1547453700,1547498640,0.27,32.47,1547484900,23.88,1547514000,37.06,1547484780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1547521200,1547540100,1547585100,0.31,31.82,1547568060,24.30,1547624580,35.44,1547567880,...,partly-cloudy-day,0.0001,0.0004,1.547532e+09,0.16,rain,1014.1,17.70,1.547585e+09,261.3
2,1547607600,1547626560,1547671500,0.34,32.50,1547654280,25.21,1547701380,36.98,1547647560,...,partly-cloudy-day,0.0001,0.0004,1.547614e+09,0.21,rain,1014.4,16.47,1.547674e+09,262.1
3,1547694000,1547712960,1547757900,0.38,32.08,1547740440,24.97,1547790240,36.63,1547740380,...,rain,0.0007,0.0054,1.547777e+09,0.35,rain,1013.6,17.16,1.547768e+09,265.7
4,1547780400,1547799420,1547844300,0.41,31.94,1547827320,24.83,1547883060,36.19,1547820240,...,rain,0.0015,0.0082,1.547781e+09,0.48,rain,1013.2,17.51,1.547841e+09,270.2

In [42]:
df.describe()

,time,sunriseTime,sunsetTime,moonPhase,temperatureHigh,temperatureHighTime,temperatureLow,temperatureLowTime,apparentTemperatureHigh,apparentTemperatureHighTime,...,apparentTemperatureMax,apparentTemperatureMaxTime,precipIntensity,precipIntensityMax,precipIntensityMaxTime,precipProbability,pressure,windGust,windGustTime,ozone
count,3.650000e+02,3.650000e+02,3.650000e+02,365.000000,365.000000,3.650000e+02,365.000000,3.650000e+02,365.000000,3.650000e+02,...,365.000000,3.650000e+02,364.000000,364.000000,3.640000e+02,364.000000,364.000000,364.000000,3.640000e+02,364.000000
mean,1.563160e+09,1.563179e+09,1.563222e+09,0.499041,30.237397,1.563204e+09,23.763096,1.563256e+09,34.150438,1.563202e+09,...,34.150438,1.563202e+09,0.004961,0.017186,1.563237e+09,0.343956,1013.826648,17.835659,1.563253e+09,264.670055
std,9.116121e+06,9.115599e+06,9.115930e+06,0.284051,1.393529,9.115246e+06,1.160211,9.113609e+06,2.535683,9.115782e+06,...,2.535683,9.115782e+06,0.008999,0.045999,9.089898e+06,0.265530,1.959726,3.619155,9.090207e+06,6.883734
min,1.547435e+09,1.547454e+09,1.547499e+09,0.000000,26.180000,1.547485e+09,20.610000,1.547514e+09,27.940000,1.547485e+09,...,27.940000,1.547485e+09,0.000000,0.000200,1.547532e+09,0.020000,1009.800000,8.740000,1.547585e+09,248.900000
25%,1.555297e+09,1.555317e+09,1.555360e+09,0.260000,29.130000,1.555344e+09,22.780000,1.555401e+09,32.040000,1.555344e+09,...,32.040000,1.555344e+09,0.000600,0.002300,1.555426e+09,0.130000,1012.300000,15.167500,1.555423e+09,259.675000
50%,1.563160e+09,1.563180e+09,1.563222e+09,0.500000,30.440000,1.563206e+09,23.880000,1.563263e+09,33.980000,1.563201e+09,...,33.980000,1.563201e+09,0.001750,0.007700,1.563223e+09,0.250000,1013.300000,17.720000,1.563260e+09,264.350000
75%,1.571022e+09,1.571040e+09,1.571084e+09,0.740000,31.410000,1.571062e+09,24.790000,1.571102e+09,36.320000,1.571062e+09,...,36.320000,1.571062e+09,0.006000,0.020425,1.571044e+09,0.502500,1015.100000,20.257500,1.571067e+09,270.000000
max,1.578884e+09,1.578903e+09,1.578948e+09,0.990000,33.070000,1.578931e+09,25.780000,1.578977e+09,39.750000,1.578931e+09,...,39.750000,1.578931e+09,0.087800,0.811500,1.578899e+09,0.990000,1019.200000,28.850000,1.578958e+09,280.400000

In [43]:
df.to_json('./my_weather_data.json', orient='records')